// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjQhk5d1y-krQggm75x3KyH-9VHbDKq2Y',
    appId: '1:199192207383:web:e3b0ffd730d16ae8aafc52',
    messagingSenderId: '199192207383',
    projectId: 'hamkorbot',
    authDomain: 'hamkorbot.firebaseapp.com',
    databaseURL: 'https://hamkorbot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hamkorbot.appspot.com',
    measurementId: 'G-NMWN3CJ5TL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc7DGCX0mYy3AvO3A6e0Znzzr-e6__VPw',
    appId: '1:199192207383:android:9bb0685347fe1accaafc52',
    messagingSenderId: '199192207383',
    projectId: 'hamkorbot',
    databaseURL: 'https://hamkorbot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hamkorbot.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVasbKgXURgfVL3MflA78TxPV55w7soS8',
    appId: '1:199192207383:ios:1fa7ea11a150aa2aaafc52',
    messagingSenderId: '199192207383',
    projectId: 'hamkorbot',
    databaseURL: 'https://hamkorbot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hamkorbot.appspot.com',
    iosClientId: '199192207383-h3vtqdr87mfphfvn7jan476llvtd5f86.apps.googleusercontent.com',
    iosBundleId: 'com.example.melo',
  );
}
